name: Ephemeral Test Pipeline

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Download code
      uses: actions/checkout@v3

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Install kubectl
      run: |
        curl -LO https://dl.k8s.io/release/stable.txt
        curl -LO https://dl.k8s.io/release/$(cat stable.txt)/bin/linux/amd64/kubectl
        chmod +x kubectl
        sudo mv kubectl /usr/local/bin/

    - name: Install kind
      run: |
        curl -Lo kind https://kind.sigs.k8s.io/dl/v0.31.0/kind-linux-amd64
        chmod +x kind
        sudo mv kind /usr/local/bin/

    - name: Create Kubernetes cluster
      run: kind create cluster

    - name: Terraform Init
      run: terraform init

    - name: Terraform Apply
      run: terraform apply -auto-approve

    - name: Verify Pods
      run: kubectl get pods

    - name: Terraform Destroy
      run: terraform destroy -auto-approve
